### ISSUE TITLE
Failed to download deb packages for Debian sid

### ISSUE THREAD

**Issue by okkez** [clear-code/cutter#28]
I've executed following setup.sh and gotten errors. I could not install cutter-testing-framework on Debian sid.

See: https://gist.github.com/okkez/192e5bf13eafe14ea2e7a3be0470a91c

**Comment by kou** [comment]
We should build Cutter instead of installing Cutter packages on sid like Groonga does: https://github.com/groonga/groonga/blob/master/data/travis/setup.sh#L22-L31

Because it's distant that we keep providing Cutter packages that work well for sid. Depended packages will be upgraded frequency on sid. And we will also need to rebuild Cutter packages for sid frequency.
